# CMake generated Testfile for 
# Source directory: /root/miniob/unittest/observer
# Build directory: /root/miniob/unittest/observer
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(aggregate_hash_table_test "/root/miniob/bin/aggregate_hash_table_test")
set_tests_properties(aggregate_hash_table_test PROPERTIES  _BACKTRACE_TRIPLES "/root/miniob/unittest/observer/CMakeLists.txt;13;add_test;/root/miniob/unittest/observer/CMakeLists.txt;0;")
add_test(arithmetic_operator_test "/root/miniob/bin/arithmetic_operator_test")
set_tests_properties(arithmetic_operator_test PROPERTIES  _BACKTRACE_TRIPLES "/root/miniob/unittest/observer/CMakeLists.txt;13;add_test;/root/miniob/unittest/observer/CMakeLists.txt;0;")
add_test(bp_manager_test "/root/miniob/bin/bp_manager_test")
set_tests_properties(bp_manager_test PROPERTIES  _BACKTRACE_TRIPLES "/root/miniob/unittest/observer/CMakeLists.txt;13;add_test;/root/miniob/unittest/observer/CMakeLists.txt;0;")
add_test(bplus_tree_log_entry_test "/root/miniob/bin/bplus_tree_log_entry_test")
set_tests_properties(bplus_tree_log_entry_test PROPERTIES  _BACKTRACE_TRIPLES "/root/miniob/unittest/observer/CMakeLists.txt;13;add_test;/root/miniob/unittest/observer/CMakeLists.txt;0;")
add_test(bplus_tree_log_test "/root/miniob/bin/bplus_tree_log_test")
set_tests_properties(bplus_tree_log_test PROPERTIES  _BACKTRACE_TRIPLES "/root/miniob/unittest/observer/CMakeLists.txt;13;add_test;/root/miniob/unittest/observer/CMakeLists.txt;0;")
add_test(bplus_tree_test "/root/miniob/bin/bplus_tree_test")
set_tests_properties(bplus_tree_test PROPERTIES  _BACKTRACE_TRIPLES "/root/miniob/unittest/observer/CMakeLists.txt;13;add_test;/root/miniob/unittest/observer/CMakeLists.txt;0;")
add_test(buffer_pool_log_test "/root/miniob/bin/buffer_pool_log_test")
set_tests_properties(buffer_pool_log_test PROPERTIES  _BACKTRACE_TRIPLES "/root/miniob/unittest/observer/CMakeLists.txt;13;add_test;/root/miniob/unittest/observer/CMakeLists.txt;0;")
add_test(chunk_test "/root/miniob/bin/chunk_test")
set_tests_properties(chunk_test PROPERTIES  _BACKTRACE_TRIPLES "/root/miniob/unittest/observer/CMakeLists.txt;13;add_test;/root/miniob/unittest/observer/CMakeLists.txt;0;")
add_test(composite_tuple_test "/root/miniob/bin/composite_tuple_test")
set_tests_properties(composite_tuple_test PROPERTIES  _BACKTRACE_TRIPLES "/root/miniob/unittest/observer/CMakeLists.txt;13;add_test;/root/miniob/unittest/observer/CMakeLists.txt;0;")
add_test(disk_buffer_pool_test "/root/miniob/bin/disk_buffer_pool_test")
set_tests_properties(disk_buffer_pool_test PROPERTIES  _BACKTRACE_TRIPLES "/root/miniob/unittest/observer/CMakeLists.txt;13;add_test;/root/miniob/unittest/observer/CMakeLists.txt;0;")
add_test(disk_log_handler_test "/root/miniob/bin/disk_log_handler_test")
set_tests_properties(disk_log_handler_test PROPERTIES  _BACKTRACE_TRIPLES "/root/miniob/unittest/observer/CMakeLists.txt;13;add_test;/root/miniob/unittest/observer/CMakeLists.txt;0;")
add_test(double_write_buffer_test "/root/miniob/bin/double_write_buffer_test")
set_tests_properties(double_write_buffer_test PROPERTIES  _BACKTRACE_TRIPLES "/root/miniob/unittest/observer/CMakeLists.txt;13;add_test;/root/miniob/unittest/observer/CMakeLists.txt;0;")
add_test(expression_test "/root/miniob/bin/expression_test")
set_tests_properties(expression_test PROPERTIES  _BACKTRACE_TRIPLES "/root/miniob/unittest/observer/CMakeLists.txt;13;add_test;/root/miniob/unittest/observer/CMakeLists.txt;0;")
add_test(log_buffer_test "/root/miniob/bin/log_buffer_test")
set_tests_properties(log_buffer_test PROPERTIES  _BACKTRACE_TRIPLES "/root/miniob/unittest/observer/CMakeLists.txt;13;add_test;/root/miniob/unittest/observer/CMakeLists.txt;0;")
add_test(log_entry_test "/root/miniob/bin/log_entry_test")
set_tests_properties(log_entry_test PROPERTIES  _BACKTRACE_TRIPLES "/root/miniob/unittest/observer/CMakeLists.txt;13;add_test;/root/miniob/unittest/observer/CMakeLists.txt;0;")
add_test(log_file_test "/root/miniob/bin/log_file_test")
set_tests_properties(log_file_test PROPERTIES  _BACKTRACE_TRIPLES "/root/miniob/unittest/observer/CMakeLists.txt;13;add_test;/root/miniob/unittest/observer/CMakeLists.txt;0;")
add_test(mvcc_trx_log_test "/root/miniob/bin/mvcc_trx_log_test")
set_tests_properties(mvcc_trx_log_test PROPERTIES  _BACKTRACE_TRIPLES "/root/miniob/unittest/observer/CMakeLists.txt;13;add_test;/root/miniob/unittest/observer/CMakeLists.txt;0;")
add_test(parser_test "/root/miniob/bin/parser_test")
set_tests_properties(parser_test PROPERTIES  _BACKTRACE_TRIPLES "/root/miniob/unittest/observer/CMakeLists.txt;13;add_test;/root/miniob/unittest/observer/CMakeLists.txt;0;")
add_test(pax_storage_test "/root/miniob/bin/pax_storage_test")
set_tests_properties(pax_storage_test PROPERTIES  _BACKTRACE_TRIPLES "/root/miniob/unittest/observer/CMakeLists.txt;13;add_test;/root/miniob/unittest/observer/CMakeLists.txt;0;")
add_test(persist_test "/root/miniob/bin/persist_test")
set_tests_properties(persist_test PROPERTIES  _BACKTRACE_TRIPLES "/root/miniob/unittest/observer/CMakeLists.txt;13;add_test;/root/miniob/unittest/observer/CMakeLists.txt;0;")
add_test(record_manager_test "/root/miniob/bin/record_manager_test")
set_tests_properties(record_manager_test PROPERTIES  _BACKTRACE_TRIPLES "/root/miniob/unittest/observer/CMakeLists.txt;13;add_test;/root/miniob/unittest/observer/CMakeLists.txt;0;")
add_test(ring_buffer_test "/root/miniob/bin/ring_buffer_test")
set_tests_properties(ring_buffer_test PROPERTIES  _BACKTRACE_TRIPLES "/root/miniob/unittest/observer/CMakeLists.txt;13;add_test;/root/miniob/unittest/observer/CMakeLists.txt;0;")
